<?php

define('FILEMAKER_UNKNOWN_ERROR', -1);
define('FILEMAKER_NO_ERROR', 0);
define('FILEMAKER_CANCELED', 1);
define('FILEMAKER_MEMORY_ERROR', 2);
define('FILEMAKER_COMMAND_UNAVAILABLE', 3);
define('FILEMAKER_COMMAND_UNKNOWN', 4);
define('FILEMAKER_COMMAND_INVALID', 5);
define('FILEMAKER_READ_ONLY', 6);
define('FILEMAKER_OUT_OF_MEMORY', 7);
define('FILEMAKER_EMPTY_RESULT', 8);
define('FILEMAKER_INSUFFICIENT_PRIVILEGES', 9);
define('FILEMAKER_MISSING_DATA', 10);
define('FILEMAKER_INVALID_NAME', 11);
define('FILEMAKER_NAME_ALREADY_EXISTS', 12);
define('FILEMAKER_IN_USE', 13);
define('FILEMAKER_OUT_OF_RANGE', 14);
define('FILEMAKER_DIVIDE_BY_ZERO', 15);
define('FILEMAKER_OPERATION_FAILED', 16);
define('FILEMAKER_CHARSET_CONVERSION_FAILED', 17);
define('FILEMAKER_MUST_PROVIDE_ACCOUNT_INFORMATION', 18);
define('FILEMAKER_NON_ASCII_STRING', 19);
define('FILEMAKER_CANCELED_BY_SCRIPT', 20);
define('FILEMAKER_NOT_SUPPORTED', 21);
define('FILEMAKER_FILE_MISSING', 100);
define('FILEMAKER_RECORD_MISSING', 101);
define('FILEMAKER_FIELD_MISSING', 102);
define('FILEMAKER_RELATIONSHIP_MISSING', 103);
define('FILEMAKER_SCRIPT_MISSING', 104);
define('FILEMAKER_LAYOUT_MISSING', 105);
define('FILEMAKER_TABLE_MISSING', 106);
define('FILEMAKER_INDEX_MISSING', 107);
define('FILEMAKER_VALUE_LIST_MISSING', 108);
define('FILEMAKER_PRIVILEGE_SET_MISSING', 109);
define('FILEMAKER_RELATED_TABLES_MISSING', 110);
define('FILEMAKER_FIELD_REPETITION_INVALID', 111);
define('FILEMAKER_WINDOW_MISSING', 112);
define('FILEMAKER_FUNCTION_MISSING', 113);
define('FILEMAKER_FILE_REFERENCE_MISSING', 114);
define('FILEMAKER_MENU_SET_MISSING', 115);
define('FILEMAKER_LAYOUT_OBJECT_MISSING', 116);
define('FILEMAKER_DATA_SOURCE_MISSING', 117);
define('FILEMAKER_THEME_MISSING', 118);
define('FILEMAKER_FILES_DAMAGED', 130);
define('FILEMAKER_LANGUAGE_PACK_MISSING', 131);
define('FILEMAKER_RECORD_ACCESS_DENIED', 200);
define('FILEMAKER_FIELD_CANNOT_BE_MODIFIED', 201);
define('FILEMAKER_FIELD_ACCESS_DENIED', 202);
define('FILEMAKER_NO_RECORDS_IN_FILE', 203);
define('FILEMAKER_NO_ACCESS_TO_FIELD_IN_SORT_ORDER', 204);
define('FILEMAKER_INSUFFICIENT_PRIVILEGES_TO_CREATE_RECORD', 205);
define('FILEMAKER_USER_DOES_NOT_HAVE_PASSWORD_CHANGE_PRIVILEGES', 206);
define('FILEMAKER_USER_DOES_NOT_HAVE_PRIVILEGES_TO_CHANGE_DATABASE_SCHEMA', 207);
define('FILEMAKER_PASSWORD_TOO_SHORT', 208);
define('FILEMAKER_NEW_PASSWORD_MUST_BE_DIFFERENT', 209);
define('FILEMAKER_ACCOUNT_IS_INACTIVE', 210);
define('FILEMAKER_PASSWORD_EXPIRED', 211);
define('FILEMAKER_INVALID_USER_ACCOUNT_OR_PASSWORD', 212);
define('FILEMAKER_USER_ACCOUNT_OR_PASSWORD_DOES_NOT_EXIST', 213);
define('FILEMAKER_TOO_MANY_LOGIN_ATTEMPTS', 214);
define('FILEMAKER_ADMIN_PRIVILEGES_CANNOT_BE_DUPLICATED', 215);
define('FILEMAKER_GUEST_ACCOUNT_CANNOT_BE_DUPLICATED', 216);
define('FILEMAKER_INSUFFICIENT_PRIVILEGES_TO_MODIFY_ADMINISTRATOR_ACCOUNT', 217);
define('FILEMAKER_PASSWORD_AND_VERIFY_PASSWORD_DO_NOT_MATCH', 218);
define('FILEMAKER_FILE_IS_LOCKED', 300);
define('FILEMAKER_RECORD_IS_IN_USE', 301);
define('FILEMAKER_TABLE_IN_USE', 302);
define('FILEMAKER_DATABASE_SCHEMA_IN_USE', 303);
define('FILEMAKER_LAYOUT_IN_USE', 304);
define('FILEMAKER_RECORD_MODIFICATION_ID_DOES_NOT_MATCH', 306);
define('FILEMAKER_COMMUNICATION_ERROR', 307);
define('FILEMAKER_THEME_IN_USE', 308);
define('FILEMAKER_FIND_CRITERIA_EMPTY', 400);
define('FILEMAKER_NO_MATCH', 401);
define('FILEMAKER_NOT_A_MATCH_FIELD', 402);
define('FILEMAKER_MAXIMUM_RECORD_LIMIT_FOR_TRIAL', 403);
define('FILEMAKER_SORT_ORDER_INVALID', 404);
define('FILEMAKER_EXCEEDS_NUMBER_OF_RECORDS_THAT_CAN_BE_OMITTED', 405);
define('FILEMAKER_REPLACE_CRITERIA_INVALID', 406);
define('FILEMAKER_ONE_OR_BOTH_MATCH_FIELDS_MISSING', 407);
define('FILEMAKER_INAPPROPRIATE_DATA_TYPE', 408);
define('FILEMAKER_IMPORT_ORDER_INVALID', 409);
define('FILEMAKER_EXPORT_ORDER_INVALID', 410);
define('FILEMAKER_WRONG_VERSION_OF_FILE_MAKER_PRO', 412);
define('FILEMAKER_INAPPROPRIATE_FIELD_TYPE', 413);
define('FILEMAKER_CANNOT_DISPLAY_RESULT', 414);
define('FILEMAKER_RELATED_RECORDS_NOT_AVAILABLE', 415);
define('FILEMAKER_PRIMARY_KEY_REQUIRED', 416);
define('FILEMAKER_NOT_A_SUPPORTED_DATA_SOURCE', 417);
define('FILEMAKER_INTERNAL_FAILURE_ON_INSERT', 418);
define('FILEMAKER_DATE_VALUE_DOES_NOT_MEET_VALIDATION', 500);
define('FILEMAKER_TIME_VALUE_DOES_NOT_MEET_VALIDATION', 501);
define('FILEMAKER_NUMBER_VALUE_DOES_NOT_MEET_VALIDATION', 502);
define('FILEMAKER_NOT_WITHIN_SPECIFIED_VALIDATION_RANGE', 503);
define('FILEMAKER_VALUE_NOT_UNIQUE', 504);
define('FILEMAKER_VALUE_NOT_AN_EXISTING', 505);
define('FILEMAKER_VALUE_NOT_LISTED_IN_THE_VALUE_LIST', 506);
define('FILEMAKER_FAILED_CALCULATION_TEST', 507);
define('FILEMAKER_INVALID_VALUE', 508);
define('FILEMAKER_FIELD_INVALID', 509);
define('FILEMAKER_VALUE_IS_EMPTY', 510);
define('FILEMAKER_EXCEEDS_MAXIMUM_FIELD_SIZE', 511);
define('FILEMAKER_RECORD_ALREADY_MODIFIED', 512);
define('FILEMAKER_DATA_CANNOT_FIT_FIELD', 513);
define('FILEMAKER_PRINT_ERROR', 600);
define('FILEMAKER_HEADER_AND_FOOTER_EXCEED_ONE_PAGE', 601);
define('FILEMAKER_BODY_DOESNT_FIT_ON_PAGE', 602);
define('FILEMAKER_PRINT_CONNECTION_LOST', 603);
define('FILEMAKER_WRONG_FILE_TYPE', 700);
define('FILEMAKER_EPSF_HAS_NO_PREVIEW_IMAGE', 706);
define('FILEMAKER_GRAPHIC_TRANSLATOR_NOT_FOUND', 707);
define('FILEMAKER_CANNOT_IMPORT_THE_FILE', 708);
define('FILEMAKER_IMPORT_TRANSLATOR_NOT_FOUND', 711);
define('FILEMAKER_PRIVILEGES_DO_NOT_ALLOW_OPERATION', 714);
define('FILEMAKER_EXCEL_WORKSHEET_OR_RANGE_IS_MISSING', 715);
define('FILEMAKER_SQL_QUERY_DELETE,_INSERT,_OR_UPDATE_IS_NOT_ALLOWED_FOR_ODBC_IMPORT', 716);
define('FILEMAKER_NOT_ENOUGH_XML_INFORMATION', 717);
define('FILEMAKER_ERROR_PARSING_XML_FILE', 718);
define('FILEMAKER_ERROR_IN_TRANSFORMING_XML', 719);
define('FILEMAKER_FORMAT_DOES_NOT_SUPPORT_REPEATING_FIELDS', 720);
define('FILEMAKER_UNKNOWN_ERROR_OCCURRED_IN_PARSER_OR_THE_TRANSFORMER', 721);
define('FILEMAKER_Cannot import data into a file that has no fields', 722);
define('FILEMAKER_You do not have permission to add records to or modify records in the target table', 723);
define('FILEMAKER_You do not have permission to add records to the target table', 724);
define('FILEMAKER_You do not have permission to modify records in the target table', 725);
define('FILEMAKER_Source file has more records than the target table; not all records were imported', 726);
define('FILEMAKER_Target table has more records than the source file; not all records were updated', 727);
define('FILEMAKER_Errors occurred during import; records could not be imported', 729);
define('FILEMAKER_Unsupported Excel version; convert file to the current Excel format and try again', 730);
define('FILEMAKER_File you are importing from contains no data', 731);
define('FILEMAKER_This file cannot be inserted because it contains other files', 732);
define('FILEMAKER_A table cannot be imported into itself', 733);
define('FILEMAKER_This file type cannot be displayed as a picture', 734);
define('FILEMAKER_This file type cannot be displayed as a picture; it will be inserted and displayed as a file', 735);
define('FILEMAKER_Too much data to export to this format; data will be truncated', 736);
define('FILEMAKER_The theme you are importing already exists', 738);
define('FILEMAKER_Unable to create file on disk', 800);
define('FILEMAKER_Unable to create temporary file on System disk', 801);
define('FILEMAKER_Unable to open file', 802);
define('FILEMAKER_File is single-user, or host cannot be found', 803);
define('FILEMAKER_File cannot be opened as read-only in its current state', 804);
define('FILEMAKER_File is damaged; use Recover command', 805);
define('FILEMAKER_File cannot be opened with this version of FileMaker Pro', 806);
define('FILEMAKER_File is not a FileMaker Pro file or is severely damaged', 807);
define('FILEMAKER_Cannot open file because access privileges are damaged', 808);
define('FILEMAKER_Disk/volume is full', 809);
define('FILEMAKER_Disk/volume is locked', 810);
define('FILEMAKER_Temporary file cannot be opened as FileMaker Pro file', 811);
define('FILEMAKER_Exceeded host’s capacity', 812);
define('FILEMAKER_Record synchronization error on network', 813);
define('FILEMAKER_File(s) cannot be opened because maximum number is open', 814);
define('FILEMAKER_Couldn’t open lookup file', 815);
define('FILEMAKER_Unable to convert file', 816);
define('FILEMAKER_Unable to open file because it does not belong to this solution', 817);
define('FILEMAKER_Cannot save a local copy of a remote file', 819);
define('FILEMAKER_File is being closed', 820);
define('FILEMAKER_Host forced a disconnect', 821);
define('FILEMAKER_FMI files not found; reinstall missing files', 822);
define('FILEMAKER_Cannot set file to single-user; guests are connected', 823);
define('FILEMAKER_File is damaged or not a FileMaker file', 824);
define('FILEMAKER_File is not authorized to reference the protected file', 825);
define('FILEMAKER_File path specified is not a valid file path', 826);
define('FILEMAKER_File was not created because the source contained no data or is a reference', 827);
define('FILEMAKER_Path is not valid for the operating system', 850);
define('FILEMAKER_Cannot delete an external file from disk', 851);
define('FILEMAKER_Cannot write a file to the external storage', 852);
define('FILEMAKER_One or more containers failed to transfer', 853);
define('FILEMAKER_General spelling engine error', 900);
define('FILEMAKER_Main spelling dictionary not installed', 901);
define('FILEMAKER_Command cannot be used in a shared file', 903);
define('FILEMAKER_Command requires a field to be active', 905);
define('FILEMAKER_Current file is not shared; command can be used only if the file is shared', 906);
define('FILEMAKER_Cannot initialize the spelling engine', 920);
define('FILEMAKER_User dictionary cannot be loaded for editing', 921);
define('FILEMAKER_User dictionary cannot be found', 922);
define('FILEMAKER_User dictionary is read-only', 923);
define('FILEMAKER_An unexpected error occurred (*)', 951);
define('FILEMAKER_Unsupported XML grammar (*)', 954);
define('FILEMAKER_No database name (*)', 955);
define('FILEMAKER_Maximum number of database sessions exceeded (*)', 956);
define('FILEMAKER_Conflicting commands (*)', 957);
define('FILEMAKER_Parameter missing (*)', 958);
define('FILEMAKER_Custom Web Publishing technology is disabled', 959);
define('FILEMAKER_Parameter is invalid', 960);
define('FILEMAKER_Generic calculation error', 1200);
define('FILEMAKER_Too few parameters in the function', 1201);
define('FILEMAKER_Too many parameters in the function', 1202);
define('FILEMAKER_Unexpected end of calculation', 1203);
define('FILEMAKER_Number, text constant, field name, or "(" expected', 1204);
define('FILEMAKER_Comment is not terminated with "*/"', 1205);
define('FILEMAKER_Text constant must end with a quotation mark', 1206);
define('FILEMAKER_Unbalanced parenthesis', 1207);
define('FILEMAKER_Operator missing, function not found, or "(" not expected', 1208);
define('FILEMAKER_Name (such as field name or layout name) is missing', 1209);
define('FILEMAKER_Plug-in function has already been registered', 1210);
define('FILEMAKER_List usage is not allowed in this function', 1211);
define('FILEMAKER_An operator (for example, +, -, *) is expected here', 1212);
define('FILEMAKER_This variable has already been defined in the Let function', 1213);
define('FILEMAKER_AVERAGE, COUNT, EXTEND, GETREPETITION, MAX, MIN, NPV, STDEV, SUM, and GETSUMMARY: expression found where a field alone is needed', 1214);
define('FILEMAKER_This parameter is an invalid Get function parameter', 1215);
define('FILEMAKER_Only summary fields are allowed as first argument in GETSUMMARY', 1216);
define('FILEMAKER_Break field is invalid', 1217);
define('FILEMAKER_Cannot evaluate the number', 1218);
define('FILEMAKER_A field cannot be used in its own formula', 1219);
define('FILEMAKER_Field type must be normal or calculated', 1220);
define('FILEMAKER_Data type must be number, date, time, or timestamp', 1221);
define('FILEMAKER_Calculation cannot be stored', 1222);
define('FILEMAKER_Function referred to is not yet implemented', 1223);
define('FILEMAKER_Function referred to does not exist', 1224);
define('FILEMAKER_Function referred to is not supported in this context', 1225);
define("The specified name can't be used", 1300);
define('FILEMAKER_A parameter of the imported or pasted function has the same name as a function in the file', 1301);
define('FILEMAKER_ODBC client driver initialization failed; make sure ODBC client drivers are properly installed', 1400);
define('FILEMAKER_Failed to allocate environment (ODBC)', 1401);
define('FILEMAKER_Failed to free environment (ODBC)', 1402);
define('FILEMAKER_Failed to disconnect (ODBC)', 1403);
define('FILEMAKER_Failed to allocate connection (ODBC)', 1404);
define('FILEMAKER_Failed to free connection (ODBC)', 1405);
define('FILEMAKER_Failed check for SQL API (ODBC)', 1406);
define('FILEMAKER_Failed to allocate statement (ODBC)', 1407);
define('FILEMAKER_Extended error (ODBC)', 1408);
define('FILEMAKER_Error (ODBC)', 1409);
define('FILEMAKER_Failed communication link (ODBC)', 1413);
define('FILEMAKER_SQL statement is too long', 1414);
define('FILEMAKER_Action requires PHP privilege extension (*)', 1450);
define('FILEMAKER_Action requires that current file be remote', 1451);
define('FILEMAKER_SMTP authentication failed', 1501);
define('FILEMAKER_Connection refused by SMTP server', 1502);
define('FILEMAKER_Error with SSL', 1503);
define('FILEMAKER_SMTP server requires the connection to be encrypted', 1504);
define('FILEMAKER_Specified authentication is not supported by SMTP server', 1505);
define('FILEMAKER_Email message(s) could not be sent successfully', 1506);
define('FILEMAKER_Unable to log in to the SMTP server', 1507);
define('FILEMAKER_Cannot load the plug-in, or the plug-in is not a valid plug-in', 1550);
define('FILEMAKER_Cannot install the plug-in; cannot delete an existing plug-in or write to the folder or disk', 1551);
define('FILEMAKER_Protocol is not supported', 1626);
define('FILEMAKER_Authentication failed', 1627);
define('FILEMAKER_There was an error with SSL', 1628);
define('FILEMAKER_Connection timed out; the timeout value is 60 seconds', 1629);
define('FILEMAKER_URL format is incorrect', 1630);
define('FILEMAKER_Connection failed', 1631);
define('FILEMAKER_The certificate has expired', 1632);
define('FILEMAKER_The certificate is self-signed', 1633);
define('FILEMAKER_A certificate verification error occurred', 1634);
